
name: Publish to DockerHub

on:
  push:
    tags: '**'
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=budgeteerorg/budgeteer
        VERSION=${GITHUB_REF#refs/tags/}
        TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=tags::${TAGS}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.prep.outputs.tags }}
